### ISSUE TITLE
Edycja kształtów

### ISSUE THREAD

**Issue by boberrs** [Creestoph/Squirrel-Math#35]
+ Przeciąganie punktów do edycji prostokąta, trójkąta, koła i wielokąta
+ Przyciąganie kształtów do innych (przyciąganie wierzchołków/ścian do pozycji x / y pobliskich punktów)
+ Edycja koloru wypełnienia i krawędzi kształtu

**Comment by Creestoph** [comment]
http://paperjs.org/

**Comment by boberrs** [comment]
2017-07-04 21:59 GMT+02:00 Creestoph <notifications@github.com>:
