### ISSUE TITLE
Update display_table script

### ISSUE THREAD

**Issue by Creestoph** [Creestoph/Squirrel-Math#57]
- [x] Rewrite script to vue component
- [x] Replace all occurances of the old script with new vue component

**Comment by Creestoph** [comment]
Script is replaced by ColumnarOperationTable.vue

**Comment by Creestoph** [comment]
See usage in Dodawanie.vue

**Comment by Creestoph** [comment]
@boberrs please replace the remaining usages of display_table with ColumnarOperationTable and close this issue

**Comment by boberrs** [comment]
W Mnożeniu, Dzieleniu i Ułamkach Dziesiętnych jest coś takiego jak
Display_table.create_custom
i pisze się trochę inaczej niż create_from_table
więc nie wiem, potrzebny osobny komponent albo jakieś rozszerzenie funkcjonalności tego co stworzyłeś

**Comment by Creestoph** [comment]
When **operation** is empty string it's treated as custom.
