### ISSUE TITLE
Update columnar_addition script

### ISSUE THREAD

**Issue by Creestoph** [Creestoph/Squirrel-Math#58]
- [x] Implement columnar addition as vue component
- [x] Replace occurances of columnar addition with new implementation

**Comment by Creestoph** [comment]
@boberrs, I'm not sure why there are 3 scripts for columnar addition - columnar_addition.js, addition_table_short.js and addition_table.js. Are any of these obsolete by any chance?

**Comment by boberrs** [comment]
Columnar addition obsługuje customowe interaktywne działania w słupku na dole strony
addition table i addition table short obsługują tabliczkę dodawania, tzn podświetlenie kratek i wynik na dole; kiedyś tam planowałeś je przepisać na czystszy kod bez rozbijania na wersję pełną/skróconą
I przestań pisać po angielsku
