### ISSUE TITLE
Write issues in english from now on

### ISSUE THREAD

**Issue by Creestoph** [Creestoph/Squirrel-Math#59]
@boberrs since your coworker (@Creestoph) have troubles expressing IT problems in polish can we please officially start writing our backlog in english?

**Comment by boberrs** [comment]
Nie, bo backlog można groomować tylko po polsku

**Comment by Creestoph** [comment]
Also it's unprofessional to write it polish, and we want our project to be professional.

**Comment by boberrs** [comment]
Jak skończymy to wykupimy tłumacza, wtedy cała strona będzie po angielsku
Jak dopłacisz to przetłumaczy ci też backlog

**Comment by Creestoph** [comment]
Content and backlog are two separate things. Backlog and code should ALWAYS be in english.

**Comment by boberrs** [comment]
Rozważ hiszpański

**Comment by Creestoph** [comment]
From now on I'll just ignore issues written in langugage other than English.
