### ISSUE TITLE
Update operation_table (addition table, etc.) script

### ISSUE THREAD

**Issue by Creestoph** [Creestoph/Squirrel-Math#62]
- [x] create single vue component for all operation tables
- [x] replace operation tables with new component

**Comment by boberrs** [comment]
To co stworzyłeś dobrze działa dla dodawania i mnożenia, ale nie widzę jaki masz pomysł żeby to uogólnić na odejmowanie i dzielenie. Przy odejmowaniu wykorzystuję tabliczkę dodawania, tylko liczby w podpisie pojawiają się w innej kolejności. Zobacz jak to działa na Webpage w Dodawaniu, Odejmowaniu, Mnożeniu i Dzieleniu (pobierz commita bo zauważyłem że przestało działać w międzyczasie). Chyba że masz inny pomysł na działanie tych tabelek niż te na Webpage.

Poza tym preferowalny do wyświetlania matematyki jest MathJax. To w sumie dotyczy wszystkich obecnych i przyszłych komponentów: żeby zachować konsekwencję, wszystkie elementy matematyczne powinny być zapisywane w dolarkach i procesowane przez refresh mathjaxa. Może przyda się jakiś bardziej ogólny system, który sam wykrywa zmiany czy coś. W kontekście operation-table mam na myśli podpis pod tabliczką, w stylu $2 \cdot 3 = 6$

**Comment by boberrs** [comment]
I jeszcze zwracam uwagę na dzielenie przez 0. Na Webpage/Dzielenie wyświetlałem komunikat "0:0 nie ma wartości"
