### ISSUE TITLE
Create Comment component to replace old comment script

### ISSUE THREAD

**Issue by Creestoph** [Creestoph/Squirrel-Math#66]
- [x] implement
- [x] test
- [x] replace old implementation

**Comment by Creestoph** [comment]
Please test first

**Comment by boberrs** [comment]
Dziwnie się zachowuje to okienko z komentarzem. Powinno być wyświetlane na wierzchu wszystkiego, nad wszystkimi innymi divami. W tej chwili ten komentarz przy kulkach jest ucinany przez tytuł rozdziału jak się najedzie na górną część słowa "Rozłóżmy". Albo zaczyna się zgniatać jak najedzie się na prawą część zdania blisko prawego marginesu lekcji. 

Poza tym źle znosi najeżdżanie na niego myszką - jak najedzie się na prostokącik z wyświetlonym komentarzem, to komentarz znika, a jeśli pod nim było zdanie opatrzone komentarzem, to zaczyna migotać.

Tak czy inaczej, mam zamieniać wszystkie <span class="comment" ...> na <comment ...>?
