### ISSUE TITLE
Implement scroll_hide functionality

### ISSUE THREAD

**Issue by Creestoph** [Creestoph/Squirrel-Math#67]
Scroll hide functionality should be implemented in:
 - lesson chapter

**Comment by Creestoph** [comment]
@boberrs anywhere else?

**Comment by boberrs** [comment]
Wygląda nieźle przy rozdziałach, jeszcze trzeba będzie w przyszłości rozszerzyć na niektóre etykietki
"Rozszerzenie", a póki co przynajmniej zapewnić im taką funkcjonalność jak na Webpage
